version: '2.0'
services:

    sockets-connection:
        build:
            context: .
            dockerfile: Dockerfile-dev
        container_name: sockets-connection
        ports:
            - "100:8080"
        volumes:
            - .:/var/www
